### ISSUE TITLE
WaiterMachine base lifetime of all wait tasks

### ISSUE THREAD

**Issue by vffuunnyy** [timoniq/telegrinder#84]
## 🚀 Feature Request 🚀

**✏️ New feature description ✏️**

Changeable base lifetime of all waiting tasks, instead of limiting their number (but they can be combined) or specifying the lifetime of each specific task.

**🪄 Provide a minimal example 🪄**

```python
class WaiterMachine:
    def __init__(self, *, max_storage_size: int = 1000, base_task_lifetime: float | timedelta | None = None) -> None:
        self.max_storage_size = max_storage_size
        self.base_task_lifetime = base_task_lifetime
        self.storage: Storage = {}
```

**✨ Teachability, Documentation, Adoption ✨**

**Comment by timoniq** [comment]
just in addition to this

max_storage_size as long as proposed lifetime parameter should be changed to attributes of storage. Storage should behave as a factory for inner limited state collectors instead of adding it like this:

https://github.com/timoniq/telegrinder/blob/96bd77057bbcc8f07d1343240be142e91f49722c/telegrinder/bot/dispatch/waiter_machine/machine.py#L95

**Comment by timoniq** [comment]
This behaviour now can be achieved via clear_wm_storage_worker that can limit lifetime of a short state

```python
bot.loop_wrapper.add_task(clear_wm_storage_worker(wm, bot.dispatch))
```
This is still unstable.  
UX will be enhanced soon but now at least `expiration_date` works independently from middleware

**Comment by timoniq** [comment]
`absolutely_dead_time` in `clear_wm_storage_worker` does the thing
